name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazelisk
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build :JdtJavaBuilder_deploy.jar

    - name: Ensure JdtJavaBuilder_deploy.jar is current
      uses: GuillaumeFalourd/diff-action@v1
      with:
        first_file_path: builder/export/JdtJavaBuilder_deploy.jar
        second_file_path: bazel-bin/JdtJavaBuilder_deploy.jar
        expected_result: PASSED

    - name: Test
      run: |
        cp -f bazel-bin/JdtJavaBuilder_deploy.jar builder/export/
        cd builder/src/test/
        "${GITHUB_WORKSPACE}/bin/bazel" test //...

