name: CI

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazelisk
        key: bazel

    - name: Build JdtJavaBuilder_deploy.jar
      run: |
        bazelisk build :JdtJavaBuilder_deploy.jar
        cp -fv bazel-bin/JdtJavaBuilder_deploy.jar compiler/export/

  test:
    needs: [build]
    
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false # we want all results
      matrix:
        compiler: [ecj, ecjtool, javac]
        java_language_version: [11, 17, 21]
        java_runtime_version: [remotejdk_11, remotejdk_17, remotejdk_21, local_jdk]
        
    steps:
    - uses: actions/checkout@v4

    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazelisk
        key: bazel

    - name: Build JdtJavaBuilder_deploy.jar
      run: |
        bazelisk build :JdtJavaBuilder_deploy.jar
        cp -fv bazel-bin/JdtJavaBuilder_deploy.jar compiler/export/

    - name: Prepare Test Compile
      run: |
        cd examples/
        echo "JAVA_HOME=$JAVA_HOME"
        java --version
        bazelisk info
        bazelisk clean

    - name: Test Compile & Test with ECJ
      if: matrix.compiler == 'ecj'
      run: |
        cd examples/
        echo "using --config=${{ matrix.compiler }} --config=debug --java_runtime_version=${{ matrix.java_runtime_version }}  --java_language_version=${{ matrix.java_language_version }}"
        bazelisk build --config=${{ matrix.compiler }} --java_runtime_version=${{ matrix.java_runtime_version }}  --java_language_version=${{ matrix.java_language_version }} //...
        bazelisk test --config=${{ matrix.compiler }} --config=debug --java_runtime_version=${{ matrix.java_runtime_version }}  --java_language_version=${{ matrix.java_language_version }} //...
      
    - name: Test Compile & Test with ECJ Tool
      if: matrix.compiler == 'ecjtool'
      run: |
        cd examples/
        echo "using --config=${{ matrix.compiler }} --config=debug --java_runtime_version=${{ matrix.java_runtime_version }}  --java_language_version=${{ matrix.java_language_version }}"
        bazelisk build --config=${{ matrix.compiler }} --java_runtime_version=${{ matrix.java_runtime_version }}  --java_language_version=${{ matrix.java_language_version }} //...
        bazelisk test --config=${{ matrix.compiler }} --config=debug --java_runtime_version=${{ matrix.java_runtime_version }}  --java_language_version=${{ matrix.java_language_version }} //...
      
    - name: Test Compile & Test with javac
      if: matrix.compiler == 'javac'
      run: |
        cd examples/
        echo "using --config=${{ matrix.compiler }} --config=debug --java_runtime_version=${{ matrix.java_runtime_version }}  --java_language_version=${{ matrix.java_language_version }}"
        bazelisk build --config=${{ matrix.compiler }} --java_runtime_version=${{ matrix.java_runtime_version }}  --java_language_version=${{ matrix.java_language_version }} //...
        bazelisk test --config=${{ matrix.compiler }} --config=debug --java_runtime_version=${{ matrix.java_runtime_version }}  --java_language_version=${{ matrix.java_language_version }} //...
        
    - name: Dump Test Logs when failed
      if: ${{ failure() }}
      run: |
        cd  examples
        find -L ./bazel-testlogs  -type f -name test.log -exec cat {} \;

    - name: Clear Test Output
      run: |
        cd examples/
        bazelisk clean
